---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: '11.16.4'
  environments_path: .chef/environments
  roles_path: .chef/roles
  data_bags_path: test/.chef/data_bags
  client_rb:
    environment: development

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    provisioner:
      client_rb:
        environment: development
    environment: development
    run_list:
      - role[development]
    attributes:
      databag_encrypted: false
